# Generated by Django 5.1.7 on 2025-03-10 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('items', '0002_alter_category_options_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='categories.category'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
