# Generated by Django 5.1.7 on 2025-03-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_listing_category_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='seller_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
