# Generated by Django 5.1.7 on 2025-03-21 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_alter_listing_category_alter_listing_category_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='listing',
            name='seller_name',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
