# Generated by Django 5.1.7 on 2025-03-20 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile.jpeg', null=True, upload_to='profile_images'),
        ),
    ]
