# Generated by Django 5.1.7 on 2025-03-20 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
    ]
